name       : hydrogen
version    : 0.9.7
release    : 8
source     :
    - https://github.com/hydrogen-music/hydrogen/archive/0.9.7.tar.gz : 1e0f3d9eae901ef5f11a61e2a446b1d819f3b38e2476a2b382cc02dea693c2b7
license    : GPL-2.0-or-later
component  : multimedia.audio
libsplit   : no
summary    : Hydrogen is an advanced drum machine
description: |
    Hydrogen is an advanced drum machine
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(libarchive)
    - pkgconfig(libpulse)
    - pkgconfig(lrdf)
    - pkgconfig(portaudio-2.0)
    - pkgconfig(QtCore)
    - pkgconfig(rubberband)
    - pkgconfig(sndfile)
    - ladspa-devel
setup      : |
    %cmake -DCMAKE_BUILD_TYPE=Release \
           -DQT_MOC_EXECUTABLE=/usr/bin/moc-qt4 \
           -DQT_RCC_EXECUTABLE=/usr/bin/rcc-qt4 \
           -DQT_UIC_EXECUTABLE=/usr/bin/uic-qt4 \
           .
build      : |
    %make
install    : |
    %make_install
