name       : hydrogen
version    : 1.2.1
release    : 17
source     :
    - https://github.com/hydrogen-music/hydrogen/archive/refs/tags/1.2.1.tar.gz : bc338a36b7119ca8caa266eeb05d8298ef7d137b7864560e32fa3fadd3d528ae
homepage   : http://hydrogen-music.org/
license    : GPL-2.0-or-later
component  : multimedia.audio
libsplit   : no
summary    : Hydrogen is an advanced drum machine
description: |
    Hydrogen is an advanced drum machine. Its main goal is to bring professional yet simple and intuitive pattern-based drum programming.
builddeps  :
    - pkgconfig(Qt5Designer)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5XmlPatterns)
    - pkgconfig(alsa)
    - pkgconfig(jack)
    - pkgconfig(libarchive)
    - pkgconfig(libpulse)
    - pkgconfig(lrdf)
    - pkgconfig(portaudio-2.0)
    - pkgconfig(rubberband)
    - pkgconfig(sndfile)
    - ladspa-devel
setup      : |
    %cmake_ninja -DCMAKE_BUILD_TYPE=Release
build      : |
    %ninja_build
install    : |
    %ninja_install
