name       : hydrogen
version    : 1.0.0
release    : 9
source     :
    - https://github.com/hydrogen-music/hydrogen/archive/1.0.0-rc1.tar.gz : 3f3abecf3b8195a16613068c43a08e435abb4052eaa5a5c94eef8121d7d85de8
license    : GPL-2.0-or-later
component  : multimedia.audio
libsplit   : no
summary    : Hydrogen is an advanced drum machine
description: |
    Hydrogen is an advanced drum machine
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(libarchive)
    - pkgconfig(libpulse)
    - pkgconfig(lrdf)
    - pkgconfig(portaudio-2.0)
    - pkgconfig(Qt5Core)
    - pkgconfig(Qt5XmlPatterns)
    - pkgconfig(rubberband)
    - pkgconfig(sndfile)
    - ladspa-devel
    - qt5-tools-devel
setup      : |
    %cmake_ninja -DCMAKE_BUILD_TYPE=Release
build      : |
    %ninja_build
install    : |
    %ninja_install
