name       : hydrogen
version    : 1.0.1
release    : 11
source     :
    - https://github.com/hydrogen-music/hydrogen/releases/download/1.0.1/hydrogen-1.0.1.tar.gz : 0a8f5ce37412293e9dce1c5f3f428f08c8d66009f40d54a6f4f6b98190e5ad20
license    : GPL-2.0-or-later
component  : multimedia.audio
libsplit   : no
summary    : Hydrogen is an advanced drum machine
description: |
    Hydrogen is an advanced drum machine
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(libarchive)
    - pkgconfig(libpulse)
    - pkgconfig(lrdf)
    - pkgconfig(portaudio-2.0)
    - pkgconfig(Qt5Core)
    - pkgconfig(Qt5XmlPatterns)
    - pkgconfig(rubberband)
    - pkgconfig(sndfile)
    - ladspa-devel
    - qt5-tools-devel
setup      : |
    %cmake_ninja -DCMAKE_BUILD_TYPE=Release
build      : |
    %ninja_build
install    : |
    %ninja_install
