name       : hydrogen
version    : 0.9.6.1
release    : 1
source     :
    - http://heanet.dl.sourceforge.net/project/hydrogen/Hydrogen/0.9.6%20Sources/hydrogen-0.9.6.1.tar.gz : 94dadf433f0abbe7e0ae8e037726b3573f8b59abf118c9c084f06c561d56b66f
license    : GPL-2.0
component  : multimedia.audio
summary    : Hydrogen is an advanced drum machine
description: |
    Hydrogen is an advanced drum machine
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(jack)
    - pkgconfig(lash-1.0)
    - pkgconfig(libpulse)
    - pkgconfig(lrdf)
    - pkgconfig(portaudio-2.0)
    - pkgconfig(QtCore)
    - pkgconfig(rubberband)
    - pkgconfig(sndfile)
    - ladspa-devel
setup      : |
    %cmake -DCMAKE_BUILD_TYPE=Release \
           -DQT_MOC_EXECUTABLE=/usr/bin/moc-qt4 \
           -DQT_RCC_EXECUTABLE=/usr/bin/rcc-qt4 \
           -DQT_UIC_EXECUTABLE=/usr/bin/uic-qt4 \
           .
build      : |
    %make
install    : |
    %make_install
