name       : hydrogen
version    : 1.1.1
release    : 15
source     :
    - https://github.com/hydrogen-music/hydrogen/releases/download/1.1.1/hydrogen-1.1.1.tar.gz : 692ef6acd94102ec9c576cf28ce8572431f669f0516c7465b6b79fc3e15e0180
license    : GPL-2.0-or-later
component  : multimedia.audio
libsplit   : no
summary    : Hydrogen is an advanced drum machine
description: |
    Hydrogen is an advanced drum machine
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(jack)
    - pkgconfig(libarchive)
    - pkgconfig(libpulse)
    - pkgconfig(lrdf)
    - pkgconfig(portaudio-2.0)
    - pkgconfig(Qt5Core)
    - pkgconfig(Qt5XmlPatterns)
    - pkgconfig(rubberband)
    - pkgconfig(sndfile)
    - ladspa-devel
    - qt5-tools-devel
setup      : |
    %cmake_ninja -DCMAKE_BUILD_TYPE=Release
build      : |
    %ninja_build
install    : |
    %ninja_install
